### ISSUE TITLE
Error When Requesting Cube of Data

### ISSUE THREAD

**Issue by Gugym** [MetOffice/qgis-plugin-edr#17] opened 2024-04-22 14:48 UTC
QGIS3.28.6, Plugin version 0.13.1.

When requesting a cube of data there is a service error.

Steps to reproduce:
Open the QGIS Plugin and go to service: https://labs.metoffice.gov/edr, select the collection Met Office (UKV) data at standard pressure levels, select an instance and a data query of cube, output of NetCDF and parameters of Air Temperature at pressure level. Define a bounding box and assign intervals of 100000.0, 1000.0, and Run the query

2024-04-22T15:40:51     CRITICAL    Environmental Data Retrieval : Error transferring https://labs.metoffice.gov.uk/edr/collections/moukv-pressure-levels/instances/2022070912/cube?crs=MO_UKV&f=NetCDF&parameter-name=air_temperature&datetime=2022-07-12T12:00:00/2022-07-14T18:00:00&z=1000.0/100000.0&bbox=-221638.7128,-622457.7093,198590.7839,-262338.7347 - server replied: Bad Request

**Comment by saberraz** [comment] 2024-04-26 08:41
Duplicate of #23

**Closed** 2024-05-10 07:12 UTC
